# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8015c7f2db210ba10739cbd83383299e9c44fa6726e9259bece5e9b2b120ddd1188a0802fb16d01b95d81de0d250dbc61057a2f02011a39ed9906b579d8df983

test:
  secret_key_base: 4b25227b298e1f54ed1f7b81fe17cec95f2f6b035412e5d172655b0e7788e0286eeb9833336347b27d06f7c5af5d2e8097b10ce98dfc05c565aab22672bbaf76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
